### ISSUE TITLE
support for repos without meta info (on object storage)

### ISSUE THREAD

**Issue by rptaylor** [cvmfs/monitor-repos#15]
https://cvmfs-monitor-frontend.web.cern.ch/  says the repo must provide meta-info. But as I understand repos hosted on S3 object storage do not have `info/v1/meta.json` because there is no server per se, only repository-level information which goes in the bucket of each repo.

Is there any way the monitor could support repos on object storage without meta info @vvolkl ?

**Comment by jblomer** [comment]
There are two different JSON artifacts. One belongs to the _server_ (https://cvmfs.readthedocs.io/en/stable/cpt-servermeta.html#global-meta-information), and this one does not usually exist for S3. What's required for the monitor is the  _repository_ related artifact (https://cvmfs.readthedocs.io/en/stable/cpt-servermeta.html#repository-specific-meta-information), which is agnostic to the infrastructure details.

**Comment by rptaylor** [comment]
Hi @jblomer !  :)  Thanks for the info.

Aha I found it via the 'M' field of the manifest: https://cvmfs.readthedocs.io/en/stable/cpt-details.html#internal-manifest-structure

**Comment by rptaylor** [comment]
I opened https://github.com/cvmfs/monitor-repos/pull/16 to fix this, please take a look.
